### ISSUE TITLE
add Software Quality tools

### ISSUE THREAD

**Issue by cefritu** [DevopsGroupC/Minitwit#111]
TODO:

at least 3 static analysis tools:
- [x] one linter for c#
- [x] one code formatter for c#
- [x] one linter for the docker files

- [x] abort build if qa is too low
- [x]  define qa quality threshhold
- [x] optional: find a tool that automatically fixes the qa problems

- [x] add Sonarqube
- [x] add Code Climate
- [x] react to the issues that these tools are complaining about

**Comment by cefritu** [comment]
Implement tasks from week07 into our code

**Comment by ebrvc** [comment]
dotnet-format
stylecop

**Comment by ebrvc** [comment]
dotnet new editorconfig

**Comment by cefritu** [comment]
C# formatting: https://dev.to/srmagura/c-linting-and-formatting-tools-in-2021-bna
Docker linting: https://medium.com/@seifeddinerajhi/creating-perfect-dockerfiles-with-hadolint-a-step-by-step-guide-to-image-optimization-25faec667884 + https://github.com/marketplace/actions/hadolint-action

**Comment by ebrvc** [comment]
Sylecop anaylsers doc:
https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/DOCUMENTATION.md

**Comment by cefritu** [comment]
First time we ran SonarCloud we had the python files still, which gave us a higher technical debt

**Comment by ebrvc** [comment]
https://codeclimate.com/github/DevopsGroupC/Minitwit

**Comment by cefritu** [comment]
https://sonarcloud.io/project/overview?id=DevopsGroupC_Minitwit
